### ISSUE TITLE
could not find the source blob

### ISSUE THREAD

**Issue by DACox17** [LandonPatmore/yahoo-fantasy-bot#101]
Getting this error when trying to create the app with Heroku.

> could not find the source blob

When I click the README links from Heroku I get a 404, so I'm wondering if the links in the app to GitHub need updated.

**Comment by VeryQueasy** [comment]
Yes, I am having this problem as well.

**Comment by LandonPatmore** [comment]
Interesting, can you try this link instead: https://heroku.com/deploy?template=https://github.com/LandonPatmore/yahoo-fantasy-bot/tree/master and see if that works?

**Comment by DACox17** [comment]
> 
> 
> Interesting, can you try this link instead: https://heroku.com/deploy?template=https://github.com/LandonPatmore/yahoo-fantasy-bot/tree/master and see if that works?

Yep, that solved the deployment error. Thanks!
