### ISSUE TITLE
Figure out how to send messages quicker

### ISSUE THREAD

**Issue by LandonPatmore** [LandonPatmore/yahoo-fantasy-bot#27]
The messaging services have limits on how many messages can be sent in a certain amount of time.  Each service waits 1000ms before sending a new message, thus slowing everything else down since it sleeps on the main thread.

Should look into what the limits are per messaging service.

**Comment by landonp1203** [comment]
Probably put the messaging services on the `Schedulers.io` thread pool so that they are no blocking the main thread.

**Comment by landonp1203** [comment]
Why I am not doing all messaging and DB accessing on background threads...I think I was sleeping...

**Comment by LandonPatmore** [comment]
Send quick enough.  If sent any faster, we will get `429` errors.
