### ISSUE TITLE
Heroku Configuration with Yahoo error

### ISSUE THREAD

**Issue by basitmohammad** [LandonPatmore/yahoo-fantasy-bot#64]
Followed all the steps and when I turned on "web" and "bot" dyno's and clicked "open app", I got hit with the screenshot below. Tried it a few times and nothing works.

![image](https://user-images.githubusercontent.com/26909671/92648988-590ab680-f2b8-11ea-9418-88367c825e07.png)

**Comment by thomann061** [comment]
I had an issue where I forgot to put the /auth after the callback url.

**Comment by LandonPatmore** [comment]
@basitmohammad Please try what @thomann061 said.  Each need step needs to be followed exactly.  Most of the times, the issue is just a configuration error on the user's end.

Please report back if you got it to work.

**Comment by LandonPatmore** [comment]
Closing because haven't heard anything back...and this just seems like a user error.
