### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by rogersa2k** [LandonPatmore/yahoo-fantasy-bot#66]
During the initial Deploy to Heroku step, after clicking the Create App button, below SLACK_WEBHOOK_URL it says Discord Web Hook URL (which it also says above for DISCORD_WEBHOOK_URL). I am still just getting this setup for the first time, and I assume it is innocuous, but it is definitely confusing.

![image](https://user-images.githubusercontent.com/4921893/92983307-94e87c00-f470-11ea-8bf7-422c7c9b8dfc.png)

Thanks!

**Comment by LandonPatmore** [comment]
Yep!  This is going to be fixed in the next update that I will hopefully get out in the next day before Sunday's game.  It will completely remove the env variables as well.

**Comment by LandonPatmore** [comment]
`v3.0.0` fixes this: https://github.com/LandonPatmore/yahoo-fantasy-bot/releases/tag/3.0.0
