### ISSUE TITLE
How do I configure the transaction alerts?

### ISSUE THREAD

**Issue by dmigliorisi** [LandonPatmore/yahoo-fantasy-bot#72]
When I try to configure the alerts I see a few options for alert type but known of them are for add/drops or trades.

<img width="260" alt="Screen Shot 2020-10-06 at 3 25 11 PM" src="https://user-images.githubusercontent.com/898450/95250464-220cbf80-07e8-11eb-8c94-f78c332622dd.png">

**Comment by LandonPatmore** [comment]
@dmigliorisi The only types of alerts that are configurable are `Score`, `Close Score`, `Standings`, and `Matchup`.  The transactions alerts, such as `add` and `drop` are always running and cannot currently be modified.

**Comment by dmigliorisi** [comment]
Got it, thanks!
