### ISSUE TITLE
Feature Request Team Name Change Notifications

### ISSUE THREAD

**Issue by aaronsewall** [LandonPatmore/yahoo-fantasy-bot#73]
I realize this isn't something yahoo provides currently but I would appreciate a feature like this. Haven't coded in kotlin before but would be willing to help wherever I can.

**Comment by LandonPatmore** [comment]
Can you give me some insight into what benefits this would have for your league?  I am more than welcoming of PRs for new features, however I would like to keep the features down to ones that would have benefits for the overall user base of the bot.
