### ISSUE TITLE
Deploy button to Heroku doesn't work

### ISSUE THREAD

**Issue by curropar** [LandonPatmore/yahoo-fantasy-bot#76]
Deploy button to Heroku doesn't work: it's pointing to https://heroku.com/deploy. I found in a [post of yours](https://www.reddit.com/r/fantasyfootball/comments/d032cw/discord_groupme_and_slack_yahoo_fantasy_football/ez5vj8s/) in Reddit that this link instead works:
https://heroku.com/deploy?template=https://github.com/landonp1203/yahoo-fantasy-bot

**Comment by LandonPatmore** [comment]
Works as intended, an issue on your end as this hasn't been an issue in a long time. Take a look here at why it points to that url: https://devcenter.heroku.com/articles/heroku-button

**Comment by curropar** [comment]
Thanks for the link! 

Not that I doubt of your word, but I don't know what issue I might have: account in Heroku was new for this little project, and I tried to deploy from two different computers, without success... Still, I got it to work with the second link, so fair enough. Thanks again!

**Comment by LandonPatmore** [comment]
You may have to clear your cookies on your browsers, that's the only thing I can think of that could possibly cause the issue.
