### ISSUE TITLE
NHL Fantasy Hockey

### ISSUE THREAD

**Issue by iancourtney** [LandonPatmore/yahoo-fantasy-bot#78]
I am trying to use this to set-up a bot for my yahoo fantasy hockey league, but I am having issues. Could it be the NHL league ID?

**Comment by LandonPatmore** [comment]
Could you attach some more information? Can you send a screenshot of the error you are seeing as well?

**Comment by iancourtney** [comment]
It is working now actually, just needed some time I guess! Thank you for making this!
