### ISSUE TITLE
Issue Finishing Bot Creation

### ISSUE THREAD

**Issue by eckoefx** [LandonPatmore/yahoo-fantasy-bot#83]
Trying to figure out what I did wrong. I'm getting the error _"An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command."_

I looked through the common issues and had to turn off the web dyno. Both web and bot are not switched to off which gives me the above message. When I turn them both on to go in and edit, it takes me to a page with a button saying "Authenticate," and when I click that I get an "Uh oh" from Yahoo.

**Comment by LandonPatmore** [comment]
It's a yahoo authentication issue. Please make sure you've followed the steps EXACTLY.

**Comment by eckoefx** [comment]
Shit. I thought I did - though the current steps are slightly different than yahoo’s new layout. 

Thanks,
Dustin
