### ISSUE TITLE
Deployed app - clicking "Authenticate" presents Yahoo "Uh oh - Looks like something went wrong. Pelase try again later"

### ISSUE THREAD

**Issue by motenoob** [LandonPatmore/yahoo-fantasy-bot#92]
Fresh deploy - variables populated with both "web" and "bot" enabled in Dynos

Yahoo_CLIENT_ID, YAHOO_CLIENT_SECRET match what's in the Yahoo Dev page
YAHOO_GAME_KEY is set to NFL
Yahoo_LEAGUE_ID matches league settings

Please let me know what I may be missing. Not sure if something changed with Yahoo's API since last year?

**Comment by LandonPatmore** [comment]
Next time, please don't delete the issue text. Comment that it was fixed, and if possible the solution as well. It will help others if they see it.
