### ISSUE TITLE
Transaction Alerts

### ISSUE THREAD

**Issue by BigCiv** [LandonPatmore/yahoo-fantasy-bot#94]
Is there a way to have the transactions alerts happen real time (within a few minutes at least)? A player was added and it didn't alert in the discord channel until 10 hours later.

**Comment by LandonPatmore** [comment]
The alerts should happen almost instantly. Interesting. Have you checked the fronted dyno to make sure it is off? If that is on, the bot will sleep. Please make sure it is off. I haven't heard of transactions taking that long. I def need more info to work on if you have it?

**Comment by BigCiv** [comment]
Awesome, thanks for the help! I missed the step where I need to turn back
off the web dyno. Just did that now.

**Comment by LandonPatmore** [comment]
No problem, if the issue persists, reopen this. Glad to hep!
