### ISSUE TITLE
Open App > Authenticate = the page isn't working error message

### ISSUE THREAD

**Issue by chrismathew21** [LandonPatmore/yahoo-fantasy-bot#97]
<img width="1422" alt="Screen Shot 2021-08-30 at 11 48 09 PM" src="https://user-images.githubusercontent.com/89798269/131443684-04dc898b-1e25-4731-9afb-1c04cea76ec4.png">
<img width="1440" alt="Screen Shot 2021-08-30 at 11 48 02 PM" src="https://user-images.githubusercontent.com/89798269/131443692-22a2fcfd-7641-41e6-b716-e190f75c677e.png">
<img width="1275" alt="Screen Shot 2021-08-30 at 11 50 21 PM" src="https://user-images.githubusercontent.com/89798269/131443881-ede60317-232a-4007-86cd-bcac3a833e46.png">
<img width="1071" alt="Screen Shot 2021-08-30 at 11 49 54 PM" src="https://user-images.githubusercontent.com/89798269/131443882-716b4de1-cd58-4b83-a9bf-7ef6110bec7a.png">

@LandonPatmore

**Comment by LandonPatmore** [comment]
For your account security, please tear the bot down, regenerate a new ID and SECRET by going through the steps again. I deleted the image with the keys you exposed. They can give access to unauthorized actors who are not as nice as I am.

**Comment by LandonPatmore** [comment]
When you run through the steps again, please follow the steps EXACTLY as they are stated. Many people miss small nuances in the auth URL section. Read over it to make sure you are doing exactly what it asks.

**Comment by ffenthusiast** [comment]
I am having the same issues. The yahoo app key page looks different then what is in the instructions:

![Screenshot 2021-08-31 163946](https://user-images.githubusercontent.com/89874807/131572780-c9bd2351-5d47-46ee-aa71-6bce3915d00e.png)

**Comment by ffenthusiast** [comment]
I am having the same issue. The yahoo developer page now looks different than the instructions have it. I have followed all the heroku instructions correctly: 
![Screenshot 2021-08-31 163946](https://user-images.githubusercontent.com/89874807/131572967-645291d6-cfe0-4504-9996-7f4146cf6580.png)

**Comment by LandonPatmore** [comment]
You can ignore the application type, looks like they removed it. Create a new one and spin up the bot and you should be good. Your auth url looks correct as well.

**Comment by ffenthusiast** [comment]
Worked once I deleted the original app and recreated it 👍

**Comment by chrismathew21** [comment]
i deleted the app and going to start over. Just to make sure, it says I need to fill out this info and then click deploy app but your instructions say to go to dashboard? Last time I filled in the info and the clicked deploy app so just wanted to make sure. @LandonPatmore 
![screencapture-dashboard-heroku-new-2021-08-31-17_11_14](https://user-images.githubusercontent.com/89798269/131582646-bd1c8a1a-8e31-40ef-822c-f7c8dfd1b029.png)

**Comment by noimjory** [comment]
Followed the instructions multiple times to get the app going and I just keep getting this whenever I try to open app

![image](https://user-images.githubusercontent.com/89879220/131585330-400e9df2-ced5-433a-bb72-433340f775b0.png)

**Comment by LandonPatmore** [comment]
@noimjory Is your web dyno on? Also can you pull up the logs for the bot and see what the issue is there and paste it here?

**Comment by chrismathew21** [comment]
I am getting the same error has as @noimjory. I turned off web dyno. Attached are my logs. 
[chrismathew-logs-1630458835107.txt](https://github.com/LandonPatmore/yahoo-fantasy-bot/files/7087546/chrismathew-logs-1630458835107.txt)

**Comment by LandonPatmore** [comment]
Yah so the logs tell all. You shut the web dyno off which means there is no endpoint to hit, thus you get this error. There is no problem with the bot itself.

If you want to change any notification times, you will need to turn the web dyno back on and wait about a minute to access it. Once you are done configuring notifications, please shut the web dyno off or the bot will actually stop working because of Heroku's policy on free accounts.
