### ISSUE TITLE
Trades not being posted by the bot

### ISSUE THREAD

**Issue by Croxy** [LandonPatmore/yahoo-fantasy-bot#98]
Hi there, thank you for the work on this!

I have the bot working, I just dropped someone and the notification went as expected.

However we just had a trade in the league and nothing came from the bot to the channel. 

Here's our list of recent transactions:

![Screen Shot 2021-08-31 at 1 34 09 PM](https://user-images.githubusercontent.com/5749114/131557402-302d83fa-69f8-4481-a568-7eba3bc71827.png)

Only the drop made it through the bot:

![Screen Shot 2021-08-31 at 1 34 25 PM](https://user-images.githubusercontent.com/5749114/131557440-15c22368-c596-439c-a8ac-63479faf344b.png)

Could there be some configuration I'm missing? Happy to provide more information if you need me to.

Thanks!

**Comment by LandonPatmore** [comment]
Do you have the web dyno on? It must be off fo the bot to work correctly, or it will shut itself down after 30min. Its a Herkou thing, so please shut that off if it is on, and restart the boy dyno.

**Comment by Croxy** [comment]
Yes, I had the web dyno off. I think that is why the drop notification worked.

**Comment by LandonPatmore** [comment]
If another trade happens and it fails again, please ping me. It has worked for others so odd it's not working for you. Did you just set the bot up?

**Comment by Croxy** [comment]
I set it up a couple of days ago. I'll try and get another of our teams to attempt a trade to see if it works. I'll update you when we can make that happen. Thanks!

**Comment by LandonPatmore** [comment]
Yah please do. I don't think Yahoo changed their API so it should pickup trades for sure. Just make sure the `web` dyno is off after authenticating.

**Comment by Croxy** [comment]
Hi Landon! I have an update for you.

Without changing any settings we were able to test another trade and the bot posted it correctly.

I wasn't able to confirm this suspicion, but I think the original issue may have to do with the fact that draft picks were included in the first trade we sent. Like I said, I can't confirm that is the issue because we weren't able to get another test trade done with draft picks. Just a suspicion. It could have totally just been a blip somewhere in the process.

I really appreciate all the work, and your quick responses to my original question. I'm going to close this thread with this comment because I don't think I'll be able to get my commish to do any more test trades before the games start.
